from typing import Annotated, Literal
from pydantic import BaseModel, Field
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages

class SQLAgentState(BaseModel):
    # استخدام add_messages عشان LangGraph يفهم كائنات الرسائل
    messages: Annotated[list[AnyMessage], add_messages] = Field(
        default_factory=list, description="List of messages processed by the agent"
    )
    curated_question: str = Field(default="", description="The curated user question")
    prompt_query_context: str = Field(default="", description="The prompt context with Databricks schema")
    generated_sql_query: str = Field(default="", description="The SQL query generated by the LLM")
    is_safe: Literal["yes", "no"] = Field(default="no", description="Indicates whether the SQL query is safe")
    comments: str = Field(default="", description="Feedback from the AI Judge")
    sql_execution_result: str = Field(default="", description="The raw result returned from Databricks")
    final_answer: str = Field(default="", description="The final natural language answer")